image: androidsdk/android-30

pipelines:
  default:
    - parallel:
        - step:
            name: Running code analysis
            caches:
              - gradle
            script:
              - cd news
              - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
              - "./gradlew lint"
            artifacts:
              - app/build/outputs/**
              - app/build/reports/**
        - step:
            name: Running tests
            caches:
              - gradle
            script:
              - cd news
              - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
              - "./gradlew test"
            artifacts:
              - app/build/outputs/**
              - app/build/reports/**
  branches:
    develop:
      - step:
          name: Creating signing keys
          script:
            - mkdir keys
            - echo $KEYSTORE_FILE_BASE64 | base64 --decode > keys/$KEYSTORE_FILE
            - echo $GOOGLE_PLAY_API_KEY_BASE64 | base64 --decode > keys/$GOOGLE_PLAY_API_KEY
          artifacts:
            - keys/**
      - step:
          name: Deploying to internal track
          deployment: Internal
          caches:
            - gradle
          script:
            - cd news
            - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
            - "./gradlew  -PkeystoreFile=../../keys/$KEYSTORE_FILE
                        -PkeystorePassword=$KEYSTORE_PASSWORD
                        -PaliasKey=$KEYSTORE_KEY_ALIAS
                        -PpasswordKey=$KEYSTORE_KEY_PASSWORD
                        -PgooglePlayKeyFile=../../keys/$GOOGLE_PLAY_API_KEY
                        -PisDevelopBranch=true
                        clean :app:publishReleaseBundle"
            - echo Performing version update
            - git add gradle.properties
            - git commit -m "[skip ci] Updating gradle.properties with the latest version"
            - git push
          artifacts:
            - app/build/outputs/
    master:
      - step:
          name: Tagging stable version
          script:
            - git tag -am "Updating tag for release build ${BITBUCKET_BUILD_NUMBER}" app-release-${BITBUCKET_BUILD_NUMBER}
            - git push origin app-release-${BITBUCKET_BUILD_NUMBER}
      - step:
          name: Deploy to production
          deployment: Production
          caches:
            - gradle
          trigger: manual
          script:
            - cd news
            - export GRADLE_OPTS='-Dorg.gradle.daemon=false'
            - "./gradlew  -PkeystoreFile=../../keys/$KEYSTORE_FILE
                          -PkeystorePassword=$KEYSTORE_PASSWORD
                          -PaliasKey=$KEYSTORE_KEY_ALIAS
                          -PpasswordKey=$KEYSTORE_KEY_PASSWORD
                          -PgooglePlayKeyFile=../../keys/$GOOGLE_PLAY_API_KEY
                          promoteReleaseArtifact --from-track internal
                          --promote-track production --release-status completed"